### PR TITLE
works also in iframes

### PR DESCRIPTION
**Pull request by latifuluman**
It also works in iframes and it's elements.

### CODE REVIEW

**Comment by trembacz** [comment]
@latifuluman thanks, appreciate that. I will check this today or tomorrow.

**Comment by trembacz** [comment]
Hi @latifuluman, what is the reason for attaching those listeners? There is already `"all_frames": true` in the `manifest.json` which should handle that.

**Comment by latifuluman** [comment]
Hi @trembacz , the current version does not inspect the elements of iframe. You can test the iframe elements in  [that](https://www.w3schools.com/w3css/tryit.asp?filename=tryw3css_borders_side) site which are in the right part of the window. By the help of the listeners, i can inspect all iframe element.

**Comment by trembacz** [comment]
Thanks @latifuluman, I've changed how to display XPath from the iframe so the user will know it's not from the main document. If you have any other ideas let me know, if not then I will merge it shortly.

**Comment by latifuluman** [comment]
Hi @trembacz . Thank you for your effort and the good project. I have no extra suggestion about this project. You can merge :)

**Pull request merged**
